### ISSUE TITLE
Separate out `nix` concepts from this package

### ISSUE THREAD

**Issue by ryantrinkle** [obsidiansystems/which#2]
This package should not be nix-specific.  It would be fine to have a `which-nix` package or something like that with nix-specific stuff, but we should not take the hackage namespace `which` for something that isn't about as general as it sounds.

**Comment by matthewbauer** [comment]
I think the only Nix-specific part here is the check for /nix/store? Otherwise we can say it is general purpose.

**Comment by ali-abrar** [comment]
There was also some nix-specific stuff in the new PR.
